import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRef, useState } from 'react';

const Home: NextPage = () => {
  const inputRef = useRef<HTMLInputElement>(null);
  const [shortURL, setShortURL] = useState('');

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (inputRef.current !== null) {
      const url = inputRef.current.value ?? '';

      await fetch('api/shortenUrl', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ url }),
      })
        .then(res => res.json())
        .then(data => {
          setShortURL(data.shortenedUrl);
        });
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>URL Shortener</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>URL Shortener</h1>

        <p className={styles.description}>Shorten here your URL&apos;s</p>

        <div className={styles.grid}>
          <form className={styles.card} onSubmit={handleSubmit}>
            <input
              ref={inputRef}
              type='text'
              className={styles.input}
              placeholder='URL'
            />
            <button>Shorten</button>
            <span>{shortURL}</span>
          </form>
        </div>
      </main>
    </div>
  );
};

export default Home;
